name: Publish to Pub.dev

on: push

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 # required!

      - name: google_map_location_picker
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.ACCESSTOKEN }}
          refreshToken: ${{ secrets.REFRESHTOKEN }}
